// Pure rendering helpers for nginx vhost configs. No I/O.

const DOMAIN_RE =
  /^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?(?:\.[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?)+$/;

export function isValidDomain(name: string): boolean {
  return DOMAIN_RE.test(name);
}

export function vhostFileName(domain: string): string {
  if (!isValidDomain(domain)) {
    throw new Error(`Invalid domain for vhost generation: ${domain}`);
  }
  return `mail-${domain.replace(/\./g, '-')}.conf`;
}

export function renderMailVhost(domain: string): string {
  if (!isValidDomain(domain)) {
    throw new Error(`Invalid domain for vhost generation: ${domain}`);
  }
  const host = `mail.${domain}`;
  const logId = host.replace(/\./g, '-');
  return `# Generated by mail-api. Do not edit by hand.
# Domain: ${domain}
server {
    listen 443 ssl;
    http2 on;
    server_name ${host};

    error_log /var/log/nginx/${logId}-error.log;
    access_log /var/log/nginx/${logId}-access.log;

    ssl_certificate /etc/letsencrypt/live/${host}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${host}/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/${host}/chain.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_session_timeout 1d;
    ssl_session_tickets off;

    client_max_body_size 50M;

    location / {
        return 403;
    }
}
`;
}
