import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import request from 'supertest';
import { existsSync, readdirSync, readFileSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { createTestDb, type TestDbHandle } from '../helpers/db';
import { createTestApp, type TestAppHandle } from '../helpers/server';

describe('NginxService.regenerate', () => {
  let h: TestDbHandle;
  let appHandle: TestAppHandle;

  beforeEach(() => {
    h = createTestDb();
    appHandle = createTestApp(h);
  });

  afterEach(() => {
    h.close();
    rmSync(appHandle.nginxGeneratedDir, { recursive: true, force: true });
  });

  it('writes a vhost per active domain', async () => {
    h.domainRepo.create({ name: 'example.com' });
    h.domainRepo.create({ name: 'example.org' });

    await appHandle.nginxService.regenerate();

    const files = readdirSync(appHandle.nginxGeneratedDir).sort();
    expect(files).toEqual(['mail-example-com.conf', 'mail-example-org.conf']);

    const content = readFileSync(
      join(appHandle.nginxGeneratedDir, 'mail-example-com.conf'),
      'utf-8',
    );
    expect(content).toContain('server_name mail.example.com;');
    expect(content).toContain('# Generated by mail-api');
  });

  it('skips inactive domains', async () => {
    const a = h.domainRepo.create({ name: 'on.com' });
    h.domainRepo.create({ name: 'off.com' });
    h.domainRepo.update(h.domainRepo.findByName('off.com')!.id, { active: false });

    await appHandle.nginxService.regenerate();

    const files = readdirSync(appHandle.nginxGeneratedDir);
    expect(files).toEqual(['mail-on-com.conf']);
    expect(a.active).toBe(true);
  });

  it('removes stale vhost files when domain becomes inactive', async () => {
    const d = h.domainRepo.create({ name: 'temp.com' });
    await appHandle.nginxService.regenerate();
    expect(existsSync(join(appHandle.nginxGeneratedDir, 'mail-temp-com.conf'))).toBe(true);

    h.domainRepo.update(d.id, { active: false });
    await appHandle.nginxService.regenerate();
    expect(existsSync(join(appHandle.nginxGeneratedDir, 'mail-temp-com.conf'))).toBe(false);
  });

  it('removes stale vhost files when domain is deleted', async () => {
    const d = h.domainRepo.create({ name: 'gone.com' });
    await appHandle.nginxService.regenerate();
    expect(existsSync(join(appHandle.nginxGeneratedDir, 'mail-gone-com.conf'))).toBe(true);

    h.domainRepo.delete(d.id);
    await appHandle.nginxService.regenerate();
    expect(existsSync(join(appHandle.nginxGeneratedDir, 'mail-gone-com.conf'))).toBe(false);
  });

  it('regenerate result reports written/removed counts', async () => {
    h.domainRepo.create({ name: 'kept.com' });
    const result1 = await appHandle.nginxService.regenerate();
    expect(result1.written).toEqual(['mail-kept-com.conf']);
    expect(result1.removed).toEqual([]);
    expect(result1.reloaded).toBe(true); // NullNginxReloader succeeds

    h.domainRepo.create({ name: 'added.com' });
    const result2 = await appHandle.nginxService.regenerate();
    expect(result2.written.sort()).toEqual(['mail-added-com.conf', 'mail-kept-com.conf']);
    expect(result2.removed).toEqual([]);
  });
});

describe('Domain CRUD triggers nginx regenerate', () => {
  let h: TestDbHandle;
  let appHandle: TestAppHandle;
  let adminKey: string;

  beforeEach(() => {
    h = createTestDb();
    appHandle = createTestApp(h);
    adminKey = h.apiKeyService.generateAndStore('admin', { scopes: ['admin'] }).plain;
  });

  afterEach(() => {
    h.close();
    rmSync(appHandle.nginxGeneratedDir, { recursive: true, force: true });
  });

  it('POST /admin/api/domains creates the vhost file', async () => {
    const res = await request(appHandle.app)
      .post('/admin/api/domains')
      .set('X-Api-Key', adminKey)
      .send({ name: 'newone.com' });

    expect(res.status).toBe(201);
    expect(existsSync(join(appHandle.nginxGeneratedDir, 'mail-newone-com.conf'))).toBe(true);
  });

  it('DELETE /admin/api/domains/:id removes the vhost file', async () => {
    const created = await request(appHandle.app)
      .post('/admin/api/domains')
      .set('X-Api-Key', adminKey)
      .send({ name: 'gone.com' });
    expect(existsSync(join(appHandle.nginxGeneratedDir, 'mail-gone-com.conf'))).toBe(true);

    await request(appHandle.app)
      .delete(`/admin/api/domains/${created.body.id}`)
      .set('X-Api-Key', adminKey);

    expect(existsSync(join(appHandle.nginxGeneratedDir, 'mail-gone-com.conf'))).toBe(false);
  });

  it('PATCH active=false removes the vhost file', async () => {
    const created = await request(appHandle.app)
      .post('/admin/api/domains')
      .set('X-Api-Key', adminKey)
      .send({ name: 'pause.com' });

    await request(appHandle.app)
      .patch(`/admin/api/domains/${created.body.id}`)
      .set('X-Api-Key', adminKey)
      .send({ active: false });

    expect(existsSync(join(appHandle.nginxGeneratedDir, 'mail-pause-com.conf'))).toBe(false);
  });
});
